CREATE TABLE customer.Identity
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(255),
    password    VARCHAR(255),
    role        VARCHAR(255),
    customer_id BIGINT,
    createdAt   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_identity PRIMARY KEY (id)
);

ALTER TABLE customer.Identity
    ADD CONSTRAINT uc_identity_customer UNIQUE (customer_id);

ALTER TABLE customer.Identity
    ADD CONSTRAINT uc_identity_username UNIQUE (username);

ALTER TABLE customer.Identity
    ADD CONSTRAINT FK_IDENTITY_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer.Customer (id);

INSERT INTO customer.Identity (username, password, role, customer_id, createdAt)
VALUES ('joao', '$2a$10$zmyGfm.SynJ/pf4NPwXHB.mmUXyzxRAld.um0ZTlryqg1W.qqdrZy', 'CUSTOMER',
        1, current_timestamp);

INSERT INTO customer.Identity (username, password, role, customer_id, createdAt)
VALUES ('mary', '$2a$10$zmyGfm.SynJ/pf4NPwXHB.mmUXyzxRAld.um0ZTlryqg1W.qqdrZy', 'CUSTOMER',
        2, current_timestamp);

INSERT INTO customer.Identity (username, password, role, customer_id, createdAt)
VALUES ('carlao', '$2a$10$zmyGfm.SynJ/pf4NPwXHB.mmUXyzxRAld.um0ZTlryqg1W.qqdrZy', 'CUSTOMER',
        3, current_timestamp);

