CREATE TABLE CustomerOrder
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    correlationalId UUID,
    status          VARCHAR(255),
    customer_id     BIGINT,
    CONSTRAINT pk_customerorder PRIMARY KEY (id)
);

ALTER TABLE CustomerOrder
    ADD CONSTRAINT uc_customerorder_correlationalid UNIQUE (correlationalId);

CREATE INDEX idx_correlationalId ON CustomerOrder (correlationalId);

ALTER TABLE CustomerOrder
    ADD CONSTRAINT FK_CUSTOMERORDER_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES Customer (id);