CREATE TABLE customer.CustomerOrder
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transactionId UUID,
    status        VARCHAR(255),
    customer_id   BIGINT,
    CONSTRAINT pk_customerorder PRIMARY KEY (id)
);

ALTER TABLE customer.CustomerOrder
    ADD CONSTRAINT uc_customerorder_transactionid UNIQUE (transactionId);

CREATE INDEX idx_transactionId ON customer.CustomerOrder (transactionId);

ALTER TABLE customer.CustomerOrder
    ADD CONSTRAINT FK_CUSTOMERORDER_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer.Customer (id);